name = "VacancyAssistedChargeTransport"
authors = ["Dilara Abdel <dilara.abdel@wias-berlin.de>"]
version = "0.1.0"

[deps]
ChargeTransport = "25c3eafe-d88c-11e9-3031-f396758f002a"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"


[compat]
ChargeTransport = "0.2.9"
ExtendableGrids = "^0.9,1"
PyPlot = "^2.0"
Roots = "^2.0"
Trapz = "^2.0.3"
julia = "^1.6"
